export type ImportantDayRule = {
  key: string
  label: string
  type: "single_day" | "date_range" | "season"
  month?: number
  day?: number
  startMonth?: number
  startDay?: number
  endMonth?: number
  endDay?: number
  note?: string
  windowDaysBefore?: number
  windowDaysAfter?: number
  promptContext: string
  priority: number
  enabled: boolean
}

export const IMPORTANT_DAYS: ImportantDayRule[] = [
  {
    key: "new_years_day",
    label: "New Year’s Day",
    type: "single_day",
    month: 1,
    day: 1,
    windowDaysBefore: 7,
    windowDaysAfter: 2,
    promptContext:
      "fresh start energy, resolutions, self-improvement pressure, reset mindset",
    priority: 90,
    enabled: true,
  },
  {
    key: "veganuary",
    label: "Veganuary",
    type: "date_range",
    startMonth: 1,
    startDay: 1,
    endMonth: 1,
    endDay: 31,
    promptContext:
      "healthy habits, food swaps, new routine ambition, trying to be better after the holidays",
    priority: 35,
    enabled: true,
  },
  {
    key: "blue_monday",
    label: "Blue Monday",
    type: "single_day",
    month: 1,
    day: 19,
    windowDaysBefore: 2,
    windowDaysAfter: 1,
    promptContext:
      "low energy, post-holiday slump, motivation dip, struggling to get going",
    priority: 45,
    enabled: true,
  },
  {
    key: "burns_night",
    label: "Burns Night",
    type: "single_day",
    month: 1,
    day: 25,
    windowDaysBefore: 2,
    windowDaysAfter: 1,
    promptContext:
      "Scottish celebration, themed plans, tradition, food and drink occasion energy",
    priority: 20,
    enabled: true,
  },
  {
    key: "valentines_day",
    label: "Valentine’s Day",
    type: "single_day",
    month: 2,
    day: 14,
    windowDaysBefore: 7,
    windowDaysAfter: 1,
    promptContext:
      "romantic pressure, gifting stress, last-minute planning, emotional expectations",
    priority: 70,
    enabled: true,
  },
  {
    key: "random_acts_of_kindness_day",
    label: "Random Acts of Kindness Day",
    type: "single_day",
    month: 2,
    day: 17,
    windowDaysBefore: 1,
    windowDaysAfter: 1,
    promptContext:
      "feel-good gestures, positivity, thoughtful actions, wholesome community energy",
    priority: 18,
    enabled: true,
  },
  {
    key: "pancake_day",
    label: "Pancake Day (Shrove Tuesday)",
    type: "single_day",
    month: 2,
    day: 17,
    windowDaysBefore: 2,
    windowDaysAfter: 1,
    promptContext:
      "treat-day excitement, comfort food, indulgence, playful food obsession",
    priority: 28,
    enabled: true,
  },
  {
    key: "lunar_new_year",
    label: "Chinese / Lunar New Year",
    type: "single_day",
    month: 2,
    day: 17,
    windowDaysBefore: 5,
    windowDaysAfter: 3,
    note: "Using provided date and label for MVP.",
    promptContext:
      "celebration, renewal, family gatherings, festive optimism, new beginning energy",
    priority: 55,
    enabled: true,
  },
  {
    key: "lgbtq_history_month_uk",
    label: "LGBTQ+ History Month (UK)",
    type: "date_range",
    startMonth: 2,
    startDay: 1,
    endMonth: 2,
    endDay: 28,
    promptContext:
      "visibility, inclusion, community pride, learning, celebration of identity and history",
    priority: 30,
    enabled: true,
  },
  {
    key: "international_womens_day",
    label: "International Women’s Day",
    type: "single_day",
    month: 3,
    day: 8,
    windowDaysBefore: 4,
    windowDaysAfter: 1,
    promptContext:
      "recognition, empowerment, appreciation, spotlight on women and achievement",
    priority: 60,
    enabled: true,
  },
  {
    key: "mothers_day_uk",
    label: "Mother’s Day (UK)",
    type: "single_day",
    month: 3,
    day: 15,
    windowDaysBefore: 7,
    windowDaysAfter: 1,
    promptContext:
      "gift planning, appreciation pressure, thoughtful gestures, family expectations",
    priority: 58,
    enabled: true,
  },
  {
    key: "st_patricks_day",
    label: "St Patrick’s Day",
    type: "single_day",
    month: 3,
    day: 17,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    promptContext:
      "celebration, social plans, pub energy, themed fun, playful chaos",
    priority: 42,
    enabled: true,
  },
  {
    key: "world_book_day_uk",
    label: "World Book Day (UK)",
    type: "single_day",
    month: 3,
    day: 5,
    windowDaysBefore: 2,
    windowDaysAfter: 1,
    promptContext:
      "school costumes, books, children’s activities, last-minute preparation",
    priority: 22,
    enabled: true,
  },
  {
    key: "ramadan",
    label: "Ramadan",
    type: "date_range",
    startMonth: 2,
    startDay: 18,
    endMonth: 3,
    endDay: 19,
    note: "Approximate dates; subject to moon sighting.",
    promptContext:
      "reflection, routine changes, fasting, community, thoughtfulness, spiritual focus",
    priority: 48,
    enabled: true,
  },
  {
    key: "april_fools_day",
    label: "April Fool’s Day",
    type: "single_day",
    month: 4,
    day: 1,
    windowDaysBefore: 2,
    windowDaysAfter: 1,
    promptContext:
      "jokes, pranks, playful deception, surprise, light-hearted chaos",
    priority: 40,
    enabled: true,
  },
  {
    key: "good_friday",
    label: "Good Friday",
    type: "single_day",
    month: 4,
    day: 3,
    windowDaysBefore: 2,
    windowDaysAfter: 0,
    promptContext:
      "long weekend mindset, slower pace, family plans, Easter build-up",
    priority: 32,
    enabled: true,
  },
  {
    key: "easter_sunday",
    label: "Easter Sunday",
    type: "single_day",
    month: 4,
    day: 5,
    windowDaysBefore: 5,
    windowDaysAfter: 1,
    promptContext:
      "family gatherings, chocolate overload, holiday treats, spring reset, long weekend energy",
    priority: 52,
    enabled: true,
  },
  {
    key: "easter_monday",
    label: "Easter Monday",
    type: "single_day",
    month: 4,
    day: 6,
    windowDaysBefore: 1,
    windowDaysAfter: 1,
    promptContext:
      "bank holiday energy, long weekend extension, low motivation, family plans",
    priority: 26,
    enabled: true,
  },
  {
    key: "earth_day",
    label: "Earth Day",
    type: "single_day",
    month: 4,
    day: 22,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    promptContext:
      "sustainability, greener choices, eco-awareness, conscious consumer thinking",
    priority: 34,
    enabled: true,
  },
  {
    key: "early_may_bank_holiday",
    label: "Early May Bank Holiday",
    type: "single_day",
    month: 5,
    day: 4,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    promptContext:
      "long weekend mood, outdoor plans, switch-off energy, short-week excitement",
    priority: 30,
    enabled: true,
  },
  {
    key: "mental_health_awareness_week_uk",
    label: "Mental Health Awareness Week (UK)",
    type: "date_range",
    startMonth: 5,
    startDay: 11,
    endMonth: 5,
    endDay: 17,
    promptContext:
      "self-care, mental overload, burnout awareness, support, wellbeing conversations",
    priority: 36,
    enabled: true,
  },
  {
    key: "eurovision_final",
    label: "Eurovision Song Contest Final",
    type: "single_day",
    month: 5,
    day: 16,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    note: "Expected date for MVP.",
    promptContext:
      "big performances, camp energy, spectacle, opinionated reactions, watch-party chaos",
    priority: 38,
    enabled: true,
  },
  {
    key: "spring_bank_holiday",
    label: "Spring Bank Holiday",
    type: "single_day",
    month: 5,
    day: 25,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    promptContext:
      "long weekend plans, travel mood, social energy, switch-off mindset",
    priority: 30,
    enabled: true,
  },
  {
    key: "pride_month",
    label: "Pride Month",
    type: "date_range",
    startMonth: 6,
    startDay: 1,
    endMonth: 6,
    endDay: 30,
    promptContext:
      "community pride, celebration, visibility, joy, inclusion, expressive energy",
    priority: 45,
    enabled: true,
  },
  {
    key: "fathers_day_uk",
    label: "Father’s Day (UK)",
    type: "single_day",
    month: 6,
    day: 21,
    windowDaysBefore: 7,
    windowDaysAfter: 1,
    promptContext:
      "gift planning, family appreciation, classic dad jokes, last-minute buying",
    priority: 50,
    enabled: true,
  },
  {
    key: "glastonbury",
    label: "Glastonbury Festival",
    type: "date_range",
    startMonth: 6,
    startDay: 24,
    endMonth: 6,
    endDay: 28,
    note: "Expected window for MVP.",
    promptContext:
      "festival chaos, mud, music obsession, group plans, camping survival energy",
    priority: 44,
    enabled: true,
  },
  {
    key: "wimbledon",
    label: "Wimbledon",
    type: "date_range",
    startMonth: 6,
    startDay: 29,
    endMonth: 7,
    endDay: 12,
    promptContext:
      "tennis season, strawberries, summer tradition, polite competition, national attention",
    priority: 40,
    enabled: true,
  },
  {
    key: "world_emoji_day",
    label: "World Emoji Day",
    type: "single_day",
    month: 7,
    day: 17,
    windowDaysBefore: 1,
    windowDaysAfter: 1,
    promptContext:
      "online expression, internet culture, texting habits, playful digital communication",
    priority: 16,
    enabled: true,
  },
  {
    key: "uk_school_summer_holidays_begin",
    label: "UK School Summer Holidays Begin",
    type: "date_range",
    startMonth: 7,
    startDay: 15,
    endMonth: 7,
    endDay: 31,
    note: "Approximate mid-to-late July window for MVP.",
    promptContext:
      "summer break chaos, childcare juggling, family outings, travel planning, routine disruption",
    priority: 33,
    enabled: true,
  },
  {
    key: "edinburgh_fringe",
    label: "Edinburgh Festival Fringe",
    type: "date_range",
    startMonth: 8,
    startDay: 1,
    endMonth: 8,
    endDay: 25,
    note: "Approximate dates for MVP.",
    promptContext:
      "performance overload, arts culture, busy city energy, packed schedules, creative buzz",
    priority: 28,
    enabled: true,
  },
  {
    key: "notting_hill_carnival",
    label: "Notting Hill Carnival",
    type: "single_day",
    month: 8,
    day: 30,
    windowDaysBefore: 2,
    windowDaysAfter: 1,
    promptContext:
      "street celebration, music, colour, crowds, high-energy community atmosphere",
    priority: 34,
    enabled: true,
  },
  {
    key: "summer_bank_holiday_uk",
    label: "Summer Bank Holiday (UK)",
    type: "single_day",
    month: 8,
    day: 31,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    promptContext:
      "final summer long weekend, making the most of it, travel plans, switch-off energy",
    priority: 31,
    enabled: true,
  },
  {
    key: "back_to_school_season",
    label: "Back to School Season",
    type: "season",
    startMonth: 9,
    startDay: 1,
    endMonth: 9,
    endDay: 10,
    note: "Approximate early September window for MVP.",
    promptContext:
      "new term prep, shopping lists, routine reset, organisation pressure, fresh-start energy",
    priority: 46,
    enabled: true,
  },
  {
    key: "freshers_week_uk",
    label: "Freshers’ Week (UK Universities)",
    type: "season",
    startMonth: 9,
    startDay: 14,
    endMonth: 9,
    endDay: 20,
    note: "Approximate mid-September window for MVP.",
    promptContext:
      "new beginnings, uni move-in chaos, social overload, independence, trying to fit in",
    priority: 25,
    enabled: true,
  },
  {
    key: "london_fashion_week",
    label: "London Fashion Week",
    type: "date_range",
    startMonth: 9,
    startDay: 18,
    endMonth: 9,
    endDay: 22,
    note: "Approximate dates for MVP.",
    promptContext:
      "trend obsession, style pressure, fashion culture, aspirational energy, aesthetic overload",
    priority: 29,
    enabled: true,
  },
  {
    key: "black_history_month_uk",
    label: "Black History Month (UK)",
    type: "date_range",
    startMonth: 10,
    startDay: 1,
    endMonth: 10,
    endDay: 31,
    promptContext:
      "recognition, reflection, celebration of history, culture, visibility and contribution",
    priority: 32,
    enabled: true,
  },
  {
    key: "oktoberfest",
    label: "Oktoberfest",
    type: "date_range",
    startMonth: 9,
    startDay: 19,
    endMonth: 10,
    endDay: 4,
    promptContext:
      "festival atmosphere, food and drink, themed fun, group outings, celebratory excess",
    priority: 20,
    enabled: true,
  },
  {
    key: "halloween",
    label: "Halloween",
    type: "single_day",
    month: 10,
    day: 31,
    windowDaysBefore: 10,
    windowDaysAfter: 1,
    promptContext:
      "spooky season, costumes, party plans, themed spending, playful chaos",
    priority: 72,
    enabled: true,
  },
  {
    key: "bonfire_night",
    label: "Bonfire Night (Guy Fawkes Night)",
    type: "single_day",
    month: 11,
    day: 5,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    promptContext:
      "fireworks, cold-weather gatherings, autumn evenings, spectacle, seasonal nostalgia",
    priority: 37,
    enabled: true,
  },
  {
    key: "movember",
    label: "Movember",
    type: "date_range",
    startMonth: 11,
    startDay: 1,
    endMonth: 11,
    endDay: 30,
    promptContext:
      "mustache challenge energy, awareness, participation, small daily commitment, community fundraising",
    priority: 24,
    enabled: true,
  },
  {
    key: "black_friday",
    label: "Black Friday",
    type: "single_day",
    month: 11,
    day: 27,
    windowDaysBefore: 10,
    windowDaysAfter: 2,
    promptContext:
      "deal urgency, discount overload, shopping rush, price-driven decisions, last-chance energy",
    priority: 100,
    enabled: true,
  },
  {
    key: "cyber_monday",
    label: "Cyber Monday",
    type: "single_day",
    month: 11,
    day: 30,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    promptContext:
      "online deal hunting, urgency, checkout pressure, digital shopping frenzy",
    priority: 85,
    enabled: true,
  },
  {
    key: "christmas_campaign_season",
    label: "Christmas Campaign Season",
    type: "date_range",
    startMonth: 12,
    startDay: 1,
    endMonth: 12,
    endDay: 24,
    promptContext:
      "gift buying, festive build-up, year-end rush, celebration planning, holiday marketing overload",
    priority: 88,
    enabled: true,
  },
  {
    key: "christmas_day",
    label: "Christmas Day",
    type: "single_day",
    month: 12,
    day: 25,
    windowDaysBefore: 7,
    windowDaysAfter: 1,
    promptContext:
      "gift stress, festive chaos, family pressure, celebration, year-end intensity",
    priority: 95,
    enabled: true,
  },
  {
    key: "boxing_day",
    label: "Boxing Day",
    type: "single_day",
    month: 12,
    day: 26,
    windowDaysBefore: 1,
    windowDaysAfter: 1,
    promptContext:
      "food coma, sale browsing, slow recovery, family leftovers, low-energy holiday mode",
    priority: 42,
    enabled: true,
  },
  {
    key: "hanukkah",
    label: "Hanukkah",
    type: "date_range",
    startMonth: 12,
    startDay: 14,
    endMonth: 12,
    endDay: 22,
    note: "Approximate dates for MVP.",
    promptContext:
      "family tradition, celebration, reflection, gifts, community, festive evenings",
    priority: 47,
    enabled: true,
  },
  {
    key: "new_years_eve",
    label: "New Year’s Eve",
    type: "single_day",
    month: 12,
    day: 31,
    windowDaysBefore: 3,
    windowDaysAfter: 1,
    promptContext:
      "party planning, end-of-year reflection, big expectations, countdown energy, fresh-start anticipation",
    priority: 92,
    enabled: true,
  },
]
