"use client";

import { useState } from "react";
import { ChevronDown } from "lucide-react";
import { cn } from "@/lib/utils";

const FAQ_ITEMS = [
  {
    question: "What does this product actually do?",
    answer:
      "Our platform generates branded memes for your business using AI. You provide context about your brand and audience, and the system creates memes designed to drive reach and engagement on social media.",
  },
  {
    question: "Can I edit the memes myself?",
    answer:
      "Not in the current version. Every meme is generated automatically using proven templates and formats so they stay true to authentic internet meme styles.",
  },
  {
    question: "Why can’t I edit the templates?",
    answer:
      "Memes work because they follow familiar formats. Allowing unlimited editing often breaks the structure that makes a meme recognizable and shareable. By generating the meme automatically, we keep the format consistent and effective.",
  },
  {
    question: "How do you keep the memes relevant?",
    answer:
      "Our system constantly monitors the internet for new viral meme formats, trends, and cultural moments. When new templates become popular, we update the system so your memes stay current.",
  },
  {
    question: "Do you update the meme templates?",
    answer:
      "Yes. Our template library is continuously updated with new formats, fonts, and styles as meme culture evolves.",
  },
  {
    question: "Will the memes match my brand?",
    answer:
      "Yes. During onboarding we learn about your business, audience, and tone. The AI uses this context to generate memes that fit your brand rather than random internet jokes.",
  },
  {
    question: "Do you generate captions as well?",
    answer:
      "Yes. Every meme can include caption suggestions so you can publish your content quickly without needing to write social copy yourself.",
  },
  {
    question: "What platforms are these memes designed for?",
    answer:
      "Memes generated by the system are designed to work across major social platforms including Instagram, Facebook, X, LinkedIn, and TikTok-style formats.",
  },
  {
    question: "Do I need design skills to use this?",
    answer:
      "No. The system handles the design, formatting, and layout automatically so you can focus on publishing great content.",
  },
];

type FAQSectionProps = Readonly<{
  "aria-labelledby"?: string;
}>;

export function FAQSection({ "aria-labelledby": ariaLabelledby }: FAQSectionProps) {
  const [openId, setOpenId] = useState<number | null>(0);

  return (
    <div
      role="region"
      aria-labelledby={ariaLabelledby}
      className="w-full"
    >
      <ul className="space-y-2">
        {FAQ_ITEMS.map((item, i) => (
          <li key={i}>
            <div className="overflow-hidden rounded-2xl border border-stone-200/80 bg-white/90 shadow-[0_8px_24px_rgba(0,0,0,0.04)]">
              <button
                type="button"
                onClick={() => setOpenId(openId === i ? null : i)}
                className="flex w-full items-center justify-between gap-3 px-4 py-3.5 text-left sm:gap-4 sm:px-5 sm:py-4"
                aria-expanded={openId === i}
              >
                <span className="text-sm font-semibold leading-snug tracking-normal text-stone-900 sm:text-[15px]">
                  {item.question}
                </span>
                <ChevronDown
                  className={cn(
                    "h-4 w-4 shrink-0 text-stone-500 transition-transform sm:h-5 sm:w-5",
                    openId === i && "rotate-180"
                  )}
                  aria-hidden
                />
              </button>
              <div
                className={cn(
                  "grid transition-[grid-template-rows] duration-200 ease-out",
                  openId === i ? "grid-rows-[1fr]" : "grid-rows-[0fr]"
                )}
              >
                <div className="min-h-0 overflow-hidden">
                  <p className="border-t border-stone-100 px-4 pb-4 pt-3 text-xs leading-relaxed text-stone-600 sm:px-5 sm:pb-4 sm:pt-3.5 sm:text-sm">
                    {item.answer}
                  </p>
                </div>
              </div>
            </div>
          </li>
        ))}
      </ul>
    </div>
  );
}
