/**
 * TEMPORARY calibration: writes PNGs with debug guides to debug-output/square-text-calibration/
 *
 * Run: npm run calibrate:square-text
 * Remove this script and renderer `debug` flag when square text layout is finalized.
 */

import { mkdir, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { wrapSquareTextMemeLines } from "../renderer/caption-wrap";
import {
  renderSquareTextMemePng,
  SQUARE_TEXT_LAYOUT_METRICS,
  SQUARE_TEXT_MAX_LINE_WIDTH_PX,
} from "../renderer/renderSquareTextMeme";
import { measureSquareTextLineWidthPx } from "../renderer/square-text-measure";

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(__dirname, "../debug-output/square-text-calibration");

/** Match production seed `square-text-v1` (slot_1_max_lines 8, single slot). */
const SLOT1_MAX = 8;
const SLOT2_MAX = 0;

const CASES: { filename: string; topText: string; notes: string }[] = [
  {
    filename: "01-short-single-line.png",
    topText: "OK.",
    notes: "Minimal single-line; should center at x=540.",
  },
  {
    filename: "02-medium-single-line.png",
    topText:
      "Your weekend plans versus Monday morning is basically two different people.",
    notes: "Fits one line (~70 chars); centered anchor.",
  },
  {
    filename: "03-balanced-two-line.png",
    topText:
      "This first line is written to be a medium length for the card. This second line mirrors that idea so wrap should split somewhat evenly.",
    notes: "Targets two lines with similar-ish length (word wrap decides).",
  },
  {
    filename: "04-awkward-two-line.png",
    topText:
      "Hi. Here comes a much longer continuation that should wrap onto additional lines and leave the first line very short compared to the rest of the block on purpose.",
    notes: "Very short first line vs long tail (ragged start).",
  },
  {
    filename: "05-three-line.png",
    topText:
      "Line one introduces a thought about homeowners and small frustrations. Line two adds a specific detail people recognize immediately without needing a picture. Line three lands the punch or observation so the card feels finished on its own.",
    notes: "Forces multi-line stack; left anchor at 112.",
  },
  {
    filename: "06-long-four-line.png",
    topText:
      "We keep adding clauses so the renderer must break across four lines or more. The goal is to stress vertical centering and the row-band guides. Nothing here should reference templates or internal jargon. It should still read like a single meme idea when you scan top to bottom on the square card.",
    notes: "Long copy; watch right-edge crowding vs 96/984 guides.",
  },
  {
    filename: "07-punctuation-heavy.png",
    topText:
      "Wait — what?! (Seriously.) 'No way'… okay, fine: maybe tomorrow. (But still: no.)",
    notes: "Dashes, quotes, parens; wrap + SVG escaping.",
  },
  {
    filename: "08-wide-vs-narrow-glyphs.png",
    topText:
      "WWWW MMMM @@@@ vs iiiiiiiiii llllllllll .... ,,,, 0000000000",
    notes: "Wide vs narrow characters; char-count wrap may not match pixel width.",
  },
];

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  const readme = `# Square text calibration (debug)

Generated by \`npm run calibrate:square-text\`.

- Guides: red verticals = left/right safe (x=96, x=984). Blue dashed = multi-line anchor (x=112). Magenta = center (x=540). Orange horizontals = y=96 and y=984 margins. Light blue bands + cyan = per-line baseline rows.

## Layout metrics (from SQUARE_TEXT_LAYOUT_METRICS)

${JSON.stringify(SQUARE_TEXT_LAYOUT_METRICS, null, 2)}

## Cases

${CASES.map((c) => `- **${c.filename}**: ${c.notes}`).join("\n")}
`;

  await writeFile(join(OUT_DIR, "README.md"), readme, "utf8");

  for (const c of CASES) {
    const buf = await renderSquareTextMemePng({
      topText: c.topText,
      bottomText: null,
      slot1MaxLines: SLOT1_MAX,
      slot2MaxLines: SLOT2_MAX,
      debug: true,
    });
    await writeFile(join(OUT_DIR, c.filename), buf);
    console.log("Wrote", join("debug-output/square-text-calibration", c.filename));

    const lines = wrapSquareTextMemeLines(
      c.topText,
      SQUARE_TEXT_MAX_LINE_WIDTH_PX,
      SLOT1_MAX
    );
    for (const line of lines) {
      const w = measureSquareTextLineWidthPx(line);
      if (w > SQUARE_TEXT_MAX_LINE_WIDTH_PX + 1) {
        console.error(
          `[calibration] Line exceeds ${SQUARE_TEXT_MAX_LINE_WIDTH_PX}px:`,
          c.filename,
          w,
          line.slice(0, 80)
        );
        process.exit(1);
      }
    }
  }

  console.log(
    "\nWidth check: all wrapped lines <=",
    SQUARE_TEXT_MAX_LINE_WIDTH_PX,
    "px (±1px)."
  );
  console.log("\nDone. Open PNGs in:", OUT_DIR);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
